const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ── GENERATE WORKSHEET ──
app.post('/api/generate', async (req, res) => {
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'API key not configured on server.' });
  }

  const { subject, level, topic, type, difficulty, language, notes, syllabus } = req.body;

  if (!subject || !level || !topic) {
    return res.status(400).json({ error: 'Subject, level, and topic are required.' });
  }

  const isBM = language === 'Bahasa Melayu';

  const systemPrompt = `You are an expert educator and curriculum specialist for Brunei's secondary school system. You create high-quality, professionally formatted worksheets perfectly aligned to the Brunei secondary curriculum — SPN21, IGCSE, and O-Level.

Your worksheets are clear, well-structured, age-appropriate, curriculum-aligned, and immediately print-ready.
${isBM ? 'Write entirely in Bahasa Melayu. Use proper formal Malay.' : 'Write in clear, academic English.'}
Output ONLY the worksheet content. No meta-commentary.`;

  const userPrompt = `Create a ${type} worksheet:

Syllabus: ${syllabus}
Subject: ${subject}
Level: ${level} (Brunei Secondary)
Topic: ${topic}
Difficulty: ${difficulty}
Language: ${language}
${notes ? `Special Instructions: ${notes}` : ''}

Include:
- Title and header (Name: ___, Date: ___, Class: ___)
- Well-numbered questions or sections
- Spacing for answers
${type === 'Practice Questions' ? '- 8-12 questions: MCQ, short answer, structured' : ''}
${type === 'Study Notes' ? '- Key concepts, definitions, examples, summary' : ''}
${type === 'Revision Checklist' ? '- Checkboxes [ ] for every concept to revise' : ''}
${type === 'Fill in the Blanks' ? '- Sentences with blanks ___ and a word bank' : ''}
- Footer: "Generated by Grade Maxing — grademaxing.bn"`;

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 2500,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }]
      })
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      return res.status(response.status).json({ error: err?.error?.message || 'API request failed.' });
    }

    const data = await response.json();
    const text = data.content?.map(b => b.text || '').join('') || '';

    if (!text) return res.status(500).json({ error: 'Empty response from AI. Try again.' });

    res.json({ worksheet: text });

  } catch (err) {
    res.status(500).json({ error: err.message || 'Server error. Please try again.' });
  }
});

// Catch-all: serve the frontend
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`✅ Grade Maxing server running on port ${PORT}`);
});
